# Generated by Django 3.1.7 on 2021-03-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_auto_20210311_2138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author', 'edition')},
        ),
    ]
