# Generated by Django 3.1.7 on 2021-03-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_auto_20210311_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'ordering': ['title', 'edition'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
