# Generated by Django 3.1.7 on 2021-03-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_auto_20210311_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'ordering': ['edition'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
