# Generated by Django 3.1.7 on 2021-03-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0007_auto_20210311_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'ordering': ['title', 'author', 'edition'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
