# Generated by Django 3.1.7 on 2021-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
