# Generated by Django 3.1.7 on 2021-03-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0011_reservation_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'ordering': ['name', 'username'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
