# Generated by Django 3.1.7 on 2021-03-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0013_auto_20210312_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': True, 'ordering': ['-reserved_at', 'book__title'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
