# Generated by Django 3.1.7 on 2021-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0014_auto_20210312_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
