# Generated by Django 3.1.7 on 2021-03-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0016_auto_20210312_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
