name: Django CI

on:
  push:
  pull_request:
    types:
      - ready_for_review
      - review_requested

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: github-actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Dependencies
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: 'Run PEP8'
      uses: quentinguidee/pep8-action@v1
      with:
        arguments: '--exclude=./*/migrations/* --max-line-length=120'

    - name: Test
      run: |
        python manage.py test --verbosity 3

    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        # Minimum allowed code coverage
        minimum-coverage: 80
